// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sharemusic.Db;

#nullable disable

namespace sharemusic.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20250829121455_UserData")]
    partial class UserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("sharemusic.Models.ArtistModel", b =>
                {
                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SpotifyId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("sharemusic.Models.GenreModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListeningHistoryModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListeningHistoryModelId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("sharemusic.Models.ListeningHistoryModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongSpotifyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongSpotifyId");

                    b.ToTable("ListeningHistory");
                });

            modelBuilder.Entity("sharemusic.Models.PlaylistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("sharemusic.Models.SongModel", b =>
                {
                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistModelSpotifyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistSpotifyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalSongPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaylistModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SongLengthInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SpotifyId");

                    b.HasIndex("ArtistModelSpotifyId");

                    b.HasIndex("GenreModelId");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("sharemusic.Models.SpotifyTokenRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpotifyTokens");
                });

            modelBuilder.Entity("sharemusic.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("sharemusic.Models.GenreModel", b =>
                {
                    b.HasOne("sharemusic.Models.ListeningHistoryModel", null)
                        .WithMany("Genre")
                        .HasForeignKey("ListeningHistoryModelId");
                });

            modelBuilder.Entity("sharemusic.Models.ListeningHistoryModel", b =>
                {
                    b.HasOne("sharemusic.Models.PlaylistModel", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sharemusic.Models.SongModel", "Song")
                        .WithMany()
                        .HasForeignKey("SongSpotifyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("sharemusic.Models.SongModel", b =>
                {
                    b.HasOne("sharemusic.Models.ArtistModel", null)
                        .WithMany("Songs")
                        .HasForeignKey("ArtistModelSpotifyId");

                    b.HasOne("sharemusic.Models.GenreModel", null)
                        .WithMany("Songs")
                        .HasForeignKey("GenreModelId");

                    b.HasOne("sharemusic.Models.PlaylistModel", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistModelId");
                });

            modelBuilder.Entity("sharemusic.Models.ArtistModel", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("sharemusic.Models.GenreModel", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("sharemusic.Models.ListeningHistoryModel", b =>
                {
                    b.Navigation("Genre");
                });

            modelBuilder.Entity("sharemusic.Models.PlaylistModel", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
